#pragma once

#define PIN_SDA GPIO_NUM_21
#define PIN_SCL GPIO_NUM_20
#define PIN_SOIL_SENSE GPIO_NUM_0
#define PIN_SOIL_PWM GPIO_NUM_9
#define PIN_BAT GPIO_NUM_1
#define PIN_BTN GPIO_NUM_2
#define BATTERY_ADC_CHANNEL ADC_CHANNEL_1
#define MOISTURE_ADC_CHANNEL ADC_CHANNEL_0

// #define PIN_SDA GPIO_NUM_21
// #define PIN_SCL GPIO_NUM_2
// #define PIN_SOIL_SENSE GPIO_NUM_0
// #define PIN_SOIL_PWM GPIO_NUM_9
// #define PIN_BAT GPIO_NUM_1
// #define BATTERY_ADC_CHANNEL ADC_CHANNEL_1
// #define MOISTURE_ADC_CHANNEL ADC_CHANNEL_0

#define PIN_RADIO_DIO1 GPIO_NUM_3
#define PIN_RADIO_BUSY GPIO_NUM_4
#define PIN_RADIO_RST GPIO_NUM_5
#define PIN_RADIO_MISO GPIO_NUM_6
#define PIN_RADIO_MOSI GPIO_NUM_7
#define PIN_RADIO_NSS GPIO_NUM_8
#define PIN_RADIO_SCK GPIO_NUM_10

#define PWM_FREQ 500000
#define NUM_ADC_READS 5